import type { Metadata } from "next";
import { Cinzel, Inter, Merriweather } from "next/font/google";
import AiyeExitIntentPopup from "@/components/aiye/AiyeExitIntentPopup";
import { SmoothScrollProvider } from "@/components/providers/SmoothScrollProvider";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Children of Aiyé — Afrofuturist Fantasy Novel | Yoruba Mythology",
  description: "Four divine Frames. One impossible soul. An Afrofuturist epic where Yoruba gods clash in future Lagos. The mythology franchise Africa deserves. Volume 1 available now.",
  keywords: [
    "Afrofuturist fantasy",
    "Yoruba mythology fiction",
    "African fantasy novel",
    "Nigerian fantasy book",
    "YA African mythology",
    "Orisha fiction",
    "Black fantasy authors",
    "African gods novel",
    "Lagos fantasy",
    "West African mythology book",
    "Children of Aiye",
    "Ola Bello author"
  ],
  authors: [{ name: "Ola Bello" }],
  creator: "Ola Bello",
  publisher: "Prose Refinery Press",
  alternates: {
    canonical: "https://proserefinery.com/children-of-aiye",
  },
  openGraph: {
    title: "Children of Aiyé — The Afrofuturist Epic Yoruba Mythology Deserves",
    description: "Four divine Frames. One impossible soul. Percy Jackson gave Greek gods a franchise. This is Africa's answer. Volume 1 available now.",
    type: "book",
    url: "https://proserefinery.com/children-of-aiye",
    siteName: "Prose Refinery",
    locale: "en_GB",
    // Image auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Children of Aiyé — Afrofuturist Fantasy Novel",
    description: "Four divine Frames. One impossible soul. The mythology franchise Africa deserves.",
    creator: "@proserefinery",
    // Image auto-generated by opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function ChildrenOfAiyeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScrollProvider>
      <div
        className={`${cinzel.variable} ${inter.variable} ${merriweather.variable} min-h-screen bg-[#0a0a0a] text-[#f0f0f0]`}
      >
        {children}
        <AiyeExitIntentPopup />
      </div>
    </SmoothScrollProvider>
  );
}
